# Form implementation generated from reading ui file 'qt_add_object.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
'''
Интерфейс диалога для внесения купленных объектов
'''
from PyQt6 import QtCore, QtGui, QtWidgets



# Класс диалогового окна
class DialogAddObject(object):
    def __init__(self):
        self.dialog = None
        self.return_ = None


    def setupUi(self, Dialog):
        self.dialog = Dialog
        Dialog.setObjectName("Dialog")
        Dialog.resize(280, 140)

        # Подписи
        font = QtGui.QFont()
        font.setPointSize(10)
        # "Тип объекта"
        self.lbl_object = QtWidgets.QLabel(parent=Dialog)
        self.lbl_object.setGeometry(QtCore.QRect(20, 20, 100, 20))
        self.lbl_object.setFont(font)
        self.lbl_object.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lbl_object.setObjectName("lbl_object")
        # "Цена"
        self.lbl_price = QtWidgets.QLabel(parent=Dialog)
        self.lbl_price.setGeometry(QtCore.QRect(20, 55, 100, 20))
        self.lbl_price.setFont(font)
        self.lbl_price.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lbl_price.setObjectName("lbl_price")

        # Ввод данных
        # Выпадающий список для выбора типа объекта
        self.cmbox_object = QtWidgets.QComboBox(parent=Dialog)
        self.cmbox_object.setGeometry(QtCore.QRect(130, 20, 130, 22))
        self.cmbox_object.setFont(font)
        self.cmbox_object.setObjectName("cmbox_object")
        self.cmbox_object.addItem("СЭС")
        self.cmbox_object.addItem("ВЭС")
        self.cmbox_object.addItem("Микрорайон")
        self.cmbox_object.addItem("Завод")
        self.cmbox_object.addItem("Больница")
        self.cmbox_object.setCurrentIndex(2)
        # Поле для ввода числа
        self.spnbox_price = QtWidgets.QDoubleSpinBox(parent=Dialog)
        self.spnbox_price.setGeometry(QtCore.QRect(130, 55, 130, 22))
        self.spnbox_price.setFont(font)
        self.spnbox_price.setObjectName("spnbox_price")

        # Кнопки
        # Сохранить
        self.btn_accept = QtWidgets.QPushButton(parent=Dialog)
        self.btn_accept.setGeometry(QtCore.QRect(20, 90, 110, 30))
        self.btn_accept.setFont(font)
        self.btn_accept.setObjectName("btn_accept")
        # Отменить
        self.btn_cancel = QtWidgets.QPushButton(parent=Dialog)
        self.btn_cancel.setGeometry(QtCore.QRect(150, 90, 110, 30))
        self.btn_cancel.setFont(font)
        self.btn_cancel.setObjectName("btn_cancel")

        self.retranslateUi(Dialog)
        self.add_functions()
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    # Перевод текста
    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Ввод купленного объекта"))
        self.lbl_price.setText(_translate("Dialog", "Цена"))
        self.lbl_object.setText(_translate("Dialog", "Тип объекта"))
        self.btn_accept.setText(_translate("Dialog", "Добавить"))
        self.btn_cancel.setText(_translate("Dialog", "Отмена"))

    # Привязка функций к интерфейсу
    def add_functions(self):
        # Неудачный выход из программы
        self.btn_cancel.clicked.connect(self.dialog.done)
        # Удачный выход из программы
        self.btn_accept.clicked.connect(self.accept_)


    # Функция удачного завершения окна
    def accept_(self):
        self.return_ = [int(self.cmbox_object.currentIndex()), float(self.spnbox_price.value())]
        self.dialog.accept()
