# Form implementation generated from reading ui file 'qt_new_objects.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
'''
Интерфейс диалога для внесения объектов игры
'''
from PyQt6 import QtCore, QtGui, QtWidgets



# Класс диалогового окна
class DialogNewObjects(object):
    def __init__(self):
        self.dialog = None
        self.return_ = None


    def setupUi(self, Dialog):
        self.dialog = Dialog
        Dialog.setObjectName("Dialog")
        Dialog.resize(300, 230)

        # Заголовки
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        # "Наименование"
        self.lbl_name = QtWidgets.QLabel(parent=Dialog)
        self.lbl_name.setGeometry(QtCore.QRect(10, 10, 140, 16))
        self.lbl_name.setFont(font)
        self.lbl_name.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_name.setObjectName("lbl_name")
        # "Количество"
        self.lbl_cnt = QtWidgets.QLabel(parent=Dialog)
        self.lbl_cnt.setGeometry(QtCore.QRect(150, 10, 140, 16))
        self.lbl_cnt.setFont(font)
        self.lbl_cnt.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_cnt.setObjectName("lbl_cnt")
        
        # Подписи
        font = QtGui.QFont()
        font.setPointSize(8)
        # "СЭС"
        self.lbl_sun = QtWidgets.QLabel(parent=Dialog)
        self.lbl_sun.setGeometry(QtCore.QRect(60, 40, 80, 20))
        self.lbl_sun.setFont(font)
        self.lbl_sun.setObjectName("lbl_sun")
        # "ВЭС"
        self.lbl_wind = QtWidgets.QLabel(parent=Dialog)
        self.lbl_wind.setGeometry(QtCore.QRect(60, 70, 80, 20))
        self.lbl_wind.setFont(font)
        self.lbl_wind.setObjectName("lbl_wind")
        # "Микрорайон"
        self.lbl_house = QtWidgets.QLabel(parent=Dialog)
        self.lbl_house.setGeometry(QtCore.QRect(60, 100, 100, 20))
        self.lbl_house.setFont(font)
        self.lbl_house.setObjectName("lbl_house")
        # "Завод"
        self.lbl_factory = QtWidgets.QLabel(parent=Dialog)
        self.lbl_factory.setGeometry(QtCore.QRect(60, 130, 80, 20))
        self.lbl_factory.setFont(font)
        self.lbl_factory.setObjectName("lbl_factory")
        # "Больница"
        self.lbl_hospital = QtWidgets.QLabel(parent=Dialog)
        self.lbl_hospital.setGeometry(QtCore.QRect(60, 160, 80, 20))
        self.lbl_hospital.setFont(font)
        self.lbl_hospital.setObjectName("lbl_hospital")

        # Выбор количества
        # СЭС
        self.spinbox_sun = QtWidgets.QSpinBox(parent=Dialog)
        self.spinbox_sun.setGeometry(QtCore.QRect(190, 40, 50, 22))
        self.spinbox_sun.setObjectName("spinbox_sun")
        # ВЭС
        self.spinbox_wind = QtWidgets.QSpinBox(parent=Dialog)
        self.spinbox_wind.setGeometry(QtCore.QRect(190, 70, 50, 22))
        self.spinbox_wind.setObjectName("spinbox_wind")
        # Микрорайон
        self.spinbox_house = QtWidgets.QSpinBox(parent=Dialog)
        self.spinbox_house.setGeometry(QtCore.QRect(190, 100, 50, 22))
        self.spinbox_house.setObjectName("spinbox_house")
        # Завод
        self.spinbox_factory = QtWidgets.QSpinBox(parent=Dialog)
        self.spinbox_factory.setGeometry(QtCore.QRect(190, 130, 50, 22))
        self.spinbox_factory.setObjectName("spinbox_factory")
        # Больница
        self.spinbox_hospital = QtWidgets.QSpinBox(parent=Dialog)
        self.spinbox_hospital.setGeometry(QtCore.QRect(190, 160, 50, 22))
        self.spinbox_hospital.setObjectName("spinbox_hospital")
        
        # Кнопки
        # Сохранить
        self.btn_accept = QtWidgets.QPushButton(parent=Dialog)
        self.btn_accept.setGeometry(QtCore.QRect(30, 190, 110, 30))
        self.btn_accept.setObjectName("btn_accept")
        # Отменить
        self.btn_cancel = QtWidgets.QPushButton(parent=Dialog)
        self.btn_cancel.setGeometry(QtCore.QRect(160, 190, 110, 30))
        self.btn_cancel.setObjectName("btn_cancel")

        self.retranslateUi(Dialog)
        self.add_functions()
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    # Перевод текста
    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Ввод объектов игры"))
        self.lbl_wind.setText(_translate("Dialog", "ВЭС"))
        self.lbl_house.setText(_translate("Dialog", "Микрорайон"))
        self.lbl_factory.setText(_translate("Dialog", "Завод"))
        self.lbl_hospital.setText(_translate("Dialog", "Больница"))
        self.lbl_sun.setText(_translate("Dialog", "СЭС"))
        self.btn_accept.setText(_translate("Dialog", "Внести"))
        self.btn_cancel.setText(_translate("Dialog", "Отмена"))
        self.lbl_name.setText(_translate("Dialog", "Наименование"))
        self.lbl_cnt.setText(_translate("Dialog", "Количество"))


    # Привязка функций к интерфейсу
    def add_functions(self):
        # Неудачный выход из программы
        self.btn_cancel.clicked.connect(self.dialog.done)
        # Удачный выход из программы
        self.btn_accept.clicked.connect(self.accept_)


    # Функция удачного завершения окна
    def accept_(self):
        self.return_ = [int(self.spinbox_sun.value()), int(self.spinbox_wind.value()), int(self.spinbox_house.value()), int(self.spinbox_factory.value()), int(self.spinbox_hospital.value())]
        self.dialog.accept()
